### PR TITLE
Polish translation

### PR DESCRIPTION
**Pull request by justmix4**
Hello, I made a Polish translation. On the first try I learned how to create a folder and file on GitHub, the final result is a complete translation into my native language. The first six commits were for learning.
Regards.

### CODE REVIEW

**Comment by justmix4** [comment]
I doo't understand why this doesn't work. I copied everything from English original file and I changed only content from English to Polish, I didn't change the code.

**Comment by julian-klode** [comment]
Hi! The problem is that you are trying to translate untranslatable strings. As the name implies, that can't work, and you'd have to remove these lines. 

Maybe I should use some online translation service where people can just sign up and translate strings in a friendly web interface, like crowdin. But that ends up with a lot of commits or loss of attribution in the commits, which is not that nice.

UI is currently a bit in a flux, with some new strings coming in in the next days, so it's probably best to wait until that is ready and then you can have a fully translated 0.5 release :)

**Comment by julian-klode** [comment]
Sorry, accidental close.

**Comment by julian-klode** [comment]
@justmix4 Strings are frozen now for the 0.5 release, so it would be great if you could rebase your work against the current master branch.

**Comment by justmix4** [comment]
Sure, Julian, in the next few days I will do it.

**Comment by justmix4** [comment]
Hi Julian. Translation is finally improved and ready for use. Regards!

**Pull request closed without merging**
