### PR TITLE
New Route66-inspired icon

### PR DESCRIPTION
**Pull request by KAMiKAZOW**

### CODE REVIEW

**Comment by julian-klode** [comment]
Ahem, that merge should not have happened. I force pushed one without it.

**Comment by julian-klode** [comment]
But oh well, let me comment on the pull request:

* CONTRIBUTING.md states that "New icons may be contributed under the GPL, version 3 or later (as below), or the Apache license, version 2.". The CC-BY-SA 4.0 license is neither.
* The icon is designed in a proprietary tool and the original source is not present, only an .svg export. If the original file were present, it would still create a vendor lock-in, though.
* Is the shadow correct, shouldn't it have some shape?
* I believe it might make sense to just have the sign icon for normal devices, without the rounded corners (use that for launchers with round icons).
* We want a just-the-sign-outline-ish icon if we merge this for displaying notifications and quick settings tiles (#62)

**Comment by KAMiKAZOW** [comment]
> CONTRIBUTING.md states that "New icons may be contributed under the GPL, version 3 or later (as below), or the Apache license, version 2.". The CC-BY-SA 4.0 license is neither.

https://www.fsf.org/blogs/licensing/creative-commons-by-sa-4-0-declared-one-way-compatible-with-gnu-gpl-version-3

> The icon is designed in a proprietary tool

No, I used Inkscape.

> original source is not present, only an .svg export.

The "original" is a Public Domain file from Wikipedia. As it's Public Domain, not even attribution is required.

> Is the shadow correct, shouldn't it have some shape?

Feel free to modify it. I would not have submitted it if it wasn't an improvement over the current icon.

**Comment by julian-klode** [comment]
Ah, so the "" comes from the sign or what? That's OK then.

The point about licensing still applies. Just because the CC-BY-SA is compatible with the GPL does not make it the GPL (it allows taking the work, modifying it, and distributing the modified stuff as GPL). Licensing is already complicated enough, I don't want to make things more complicated by adding a third license (not to mention, adding the license text itself).

**Comment by KAMiKAZOW** [comment]
You have hereby my consent for the GPLv3+ (whether GPLv3+ only or CC dual licensing – I don't care). You may modify the metadata accordingly.

**Pull request merged**
