### PR TITLE
Norwegian translation

### PR DESCRIPTION
**Pull request by DandelionSprout**
I created a Norwegian translation for DNS66, based on what I could see of how the other translations on GitHub did it.

Note: Language ISO codes for Norwegian are slightly messy, so I wasn't sure whether to name the folder "values-nb" or "values-no" in order for the translation to be used for Norwegian Android users.

### CODE REVIEW

**Comment by julian-klode** [comment]
Hmm, complicated. From the ISO side, 

no – inclusive code
nb – Bokmål
nn – Nynorsk

But I'm not sure how Android maps those.

**Comment by julian-klode** [comment]
CI is failing, there's some issues in the xml. Please push updates and keep a look on the CI report here.

**Comment by DandelionSprout** [comment]
The CI report claims that a <resources> element is unclosed, despite how I can see that it indeed is closed (Lines 1 and 108 in the strings.xml).

It's written in the Bokmål standard, which rules out "nn". While I presume that both "no" and "nb" can be used, I suppose you could use "nb" for safety's sake?

**Comment by julian-klode** [comment]
I have not tried it, but maybe I could just symlink values-no and values-nn to values-nb in the meantime, so there's no fallback to English.

**Comment by julian-klode** [comment]
Here's the problem:
```
    <string name="translator_credits"/>Imre Kristoffer Eilertsen</string>
```

You are closing string twice, and it now matches the `</string>` to `<resources>` and complains that it should be closed with `</resources>` instead. Which is not particularly useful, as the problem is that the string is closed in the opening tag.

**Comment by DandelionSprout** [comment]
Ah. I see. Brb.

**Comment by julian-klode** [comment]
Note that is says:
```
+    <!-- Translate with something like <Language> Translation: Your Name -->
```

It seems there's only your name in it? That looks weird in the about view.

**Comment by DandelionSprout** [comment]
I think I should've got it right by now. I hope.

**Pull request merged**
