### PR TITLE
Add Chinese translation

### PR DESCRIPTION
**Pull request by KevinSJ**
Fix some untranslated part

### CODE REVIEW

**Comment by KevinSJ** [comment]
I agree with the contribution terms.

**Comment by julian-klode** [comment]
Thanks that looks fine. I added a comment to #12 as I did not notice you already opened a new one. Shall I first add a translator credit thingy, and then you can specify your translator credits as a string, before merging the pull request? Makes sense, right?

**Comment by KevinSJ** [comment]
Sorry about opening a new pr, I am not quite familiar with contributing stuff. That sounds good to me, or you can just merge this first and then use Kevin as my name for Chinese translator later.

**Comment by julian-klode** [comment]
OK, I pushed some early translator credit support now. If you pull things, you'll notice that there's a new string translator_credits that you can translate with something like 

<your language> translation: <your name>

That will then appear in the Info screen. It also supports multiple names in theory, but in practice the formatting is a bit weird right now, because it's centered.

**Comment by julian-klode** [comment]
I can just squash merge the change for you before you go mad of all the merging work. 

But for the record, the optimal solution would have no merges on your side, that is, you'd have to rebase, and then have one commit adding the translation. 

On the command line that's something like running "git pull --rebase=interactive" and then picking the first commit and marking the others as fix up commits.

**Comment by KevinSJ** [comment]
Thanks for helping with that, I was just really confused by these things.

**Comment by julian-klode** [comment]
Thanks for your contribution.

**Pull request closed without merging**
