### PR TITLE
Dutch translation

### PR DESCRIPTION
**Pull request by RoySchutte**
The current Dutch (Belgium) translations are somewhat bad (grammatically). Please use these (at least for values-nl-rNL).

### CODE REVIEW

**Comment by julian-klode** [comment]
@RoySchutte The nl-rBE translation was done by @Ox0000 - I'd like to get some input. I am curious if I should replace nl-rBE with just nl or not, I don't really know the differences between "standard" and Belgian Dutch (this thing is mostly technical, I'd be surprised if there are any important ones).

**Comment by RoySchutte** [comment]
Hi @julian-klode,

I should have explained better. NL-NL (Dutch) and NL-BE (Belgian) are grammatically nearly identical (a few exceptions). We speak the 'same' language. It's more like a different accent, like English and American.

The grammatical errors I'm seeing apply to both languages. However, I see that @Ox0000 also used a few words that are uncommon in Dutch, and more common in Belgian. As I am Dutch, I changed those words too.

What I tried to say in the original pull comment is:
1. Please (at least) use my translations for nl-rNL.
2. Optional: Replace the Belgian file with mine as well, to get rid of the grammatical errors. Ox0000 (or any other contributer) can change the common Dutch words back to Belgian if he/she wishes.

**Comment by RoySchutte** [comment]
Made small changes to make descriptions clearer for users.

**Comment by julian-klode** [comment]
The review still stands. If you want this merged, please fix the build failure.

**Pull request merged**
